name: Run Ticket Scraper

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs the job every 15 minutes
  schedule:
    - cron: '*/15 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          playwright install

      - name: Run ticket scraper script
        id: script
        env:
          PUSHBULLET_TOKENS_JSON: ${{ secrets.PUSHBULLET_TOKENS_JSON }}
        run: |
          python main.py

      # --- FIX: Updated commit step to prevent push errors ---
      - name: Commit and push if there are changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tickets_summary_log.csv
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            # If there are changes, commit them
            git commit -m "Update ticket summary log"
            # Pull the latest changes from the remote repository before pushing
            # to avoid the "fetch first" error. --rebase replays our commit on top.
            git pull --rebase
            # Push the changes
            git push
          fi
      
      # --- NEW: Upload debug screenshot on failure ---
      - name: Upload Debug Screenshot
        # This step will only run if the previous script step failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshot
          path: debug_screenshot.png
